core/urls.py
from django.urls import path

from .views import *

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

app_name = "core"

urlpatterns = [
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
                  path('invite/', InvitationView.as_view(), name = 'invite'),
                  path('course/', CourseView.as_view(), name='course'),
                  path('course-create/', CourseCreateView.as_view(), name='course-create'),                  
                  path('assignment-create/', AssignmentCreateView.as_view(), name='assignment-create'),
                  path('assignment/', AssignmentView.as_view(), name='assignment-list'),
                  path('<pk>/delete/', AssignmentDeleteView.as_view(), name='delete-assignment'),
                  path('assignment-submission/', AssignmentSubmissionView.as_view(), name='assignment-submission'),
                  path('assignment-submission-list/', AssignmentSubmissionListView, name='assignment-submission-list'),
                  path('<pk>/delete/', AssignmentSubmissionDelete.as_view(), name='assignment-submission-delete'),
                  path('assignment/feedback/',FeedbackSubmission,name='assignment-feedback'),
                  path('addInForum/',addInForum,name='addInForum'),
                  path('addInDiscussion/',addInDiscussion,name='addInDiscussion'),
                  path('ViewForum/',ViewForum,name='ViewForum'),
                 # path('ViewStats/',CourseStats,name='ViewStats'),
                  
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floatmoodle2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('core.urls', namespace='core')),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), 
        name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms

from core.models import AssignmentSubmission, Feedback
from .models import *


class InvitationForm(forms.ModelForm):
    class Meta:
        model = Invitation
        fields = ['sname', 'email']

    def __init__(self, *args, **kwargs):
        super(InvitationForm, self).__init__(*args, **kwargs)
        self.fields['sname'].label = "Student Name"
        self.fields['email'].label = "Student Email"

        self.fields['sname'].widget.attrs.update(
            {
                'placeholder': 'Enter Student Name',
            }
        )

        self.fields['email'].widget.attrs.update(
            {
                'placeholder': 'Enter Student Email',
            }
        )

    def is_valid(self):
        valid = super(InvitationForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(InvitationForm, self).save(commit=False)
        if commit:
            course.save()
        return course

class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_description', 'end_date']

    def __init__(self, *args, **kwargs):
        super(CourseCreateForm, self).__init__(*args, **kwargs)
        self.fields['course_name'].label = "Course Name"
        self.fields['course_description'].label = "Description"
        self.fields['end_date'].label = "End Date"

        self.fields['course_name'].widget.attrs.update(
            {
                'placeholder': 'Enter Course Name',
            }
        )

        self.fields['course_description'].widget.attrs.update(
            {
                'placeholder': 'Description',
            }
        )

    def is_valid(self):
        valid = super(CourseCreateForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(CourseCreateForm, self).save(commit=False)
        if commit:
            course.save()
        return course

        
# ASSIGNMENT CREATE FORM
class AssignmentCreateForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['Course','title', 'content', 'weight', 'duration','end_at']
        #fields = ['title', 'content', 'marks', 'duration']

    

    def is_valid(self):
        valid = super(AssignmentCreateForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(AssignmentCreateForm, self).save(commit=False)
        if commit:
            course.save()
        return course

class AssignmentSubmissionForm(forms.ModelForm):
    class Meta:
        model= AssignmentSubmission
        fields = ['Assignment','content','file']

    def is_valid(self):
        valid = super(AssignmentSubmissionForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(AssignmentSubmissionForm, self).save(commit=False)
        if commit:
            course.save()
        return course




class FeedbackForm(forms.ModelForm):
    class Meta:
        model= Feedback
        fields = "__all__"

    def is_valid(self):
        valid = super(FeedbackForm, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(FeedbackForm, self).save(commit=False)
        if commit:
            course.save()
        return course



class CreateInForum(forms.ModelForm):
    class Meta:
        model= forum
        fields = ['topic']
    
    def is_valid(self):
        valid = super(CreateInForum, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(CreateInForum, self).save(commit=False)
        if commit:
            course.save()
        return course

 
class CreateInDiscussion(forms.ModelForm):
    class Meta:
        model= Discussion
        fields = ['forum','discuss']

    def is_valid(self):
        valid = super(CreateInDiscussion, self).is_valid()

        # if already valid, then return True
        if valid:
            return valid
        return valid

    def save(self, commit=True):
        course = super(CreateInDiscussion, self).save(commit=False)
        if commit:
            course.save()
        return course

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.http import Http404
from authentication.decorators import user_is_instructor, user_is_student
from core.forms import FeedbackForm
from core.models import AssignmentSubmission

from .forms import *
from .models import *

from .decorators import user_is_student, user_is_instructor
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy

from django.core.mail import EmailMessage, send_mail



class InvitationView(CreateView):
    template_name = 'core/instructor/invite.html'
    form_class = InvitationForm
    extra_context = {
        'title': 'New Course'
    }
    success_url = reverse_lazy('core:home')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(InvitationView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            x = form.save(commit=False)

            email_subject = "Invitation to join Float Moodle"
            email_body = f"Hi {x.sname}, You are invited to join float moodle by your professor. Follow this link to register as a student: https://floatmoodle-team-rocket.herokuapp.com/student/register"
            email = EmailMessage(
                email_subject,
                email_body,
                'noreply@moodle.com',
                [x.email]
            )
            email.send(fail_silently=False)
    
            return self.form_valid(form)
        else:
            return self.form_invalid(form)




# COURSE CREATE VIEW
class CourseCreateView(CreateView):
    template_name = 'core/instructor/course_create.html'
    form_class = CourseCreateForm
    extra_context = {
        'title': 'New Course'
    }
    success_url = reverse_lazy('core:course')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CourseCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CourseView(ListView):
    model = Course
    template_name = 'core/instructor/courses.html'
    context_object_name = 'course'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_instructor, user_is_student)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all().order_by('-id')  # filter(user_id=self.request.user.id).order_by('-id')


# ASSIGNMENT CREATE VIEW
class AssignmentCreateView(CreateView):
    template_name = 'core/instructor/assignment_create.html'
    form_class = AssignmentCreateForm
    extra_context = {
        'title': 'New Course'
    }
    success_url = reverse_lazy('core:assignment-list')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'instructor':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AssignmentCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


# VIEW FOR ASSIGNMENT LIST
class AssignmentView(ListView):
    model = Assignment
    template_name = 'core/instructor/assignments.html'
    context_object_name = 'assignment'

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    # @method_decorator(user_is_student, user_is_instructor)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.all()  # filter(user_id=self.request.user.id).order_by('-id')


# DELETE ASSIGNMENT VIEW
class AssignmentDeleteView(DeleteView):
    model = Assignment
    success_url = reverse_lazy('core:assignment-list')


# ASSIGNMENT SUBMISSION VIEW
class AssignmentSubmissionView(CreateView):
    template_name = 'core/instructor/assignment_submission.html'
    form_class = AssignmentSubmissionForm
    extra_context = {
        'title': 'New Exam'
    }
    success_url = reverse_lazy('core:home')

    @method_decorator(login_required(login_url=reverse_lazy('authentication:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('authentication:login')
        if self.request.user.is_authenticated and self.request.user.role != 'student':
            return reverse_lazy('authentication:login')
        return super().dispatch(self.request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AssignmentSubmissionView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)




def AssignmentSubmissionListView(request):
    assignment_submission=AssignmentSubmission.objects.all()
    #count=foru.count()
    feedbacks=[]
    for i in assignment_submission:
        feedbacks.append(i.feedback_set.all())
 
    context={'assignment_submission':assignment_submission,'feedbacks':feedbacks}
    return render(request,'core/instructor/assignment_submission_list.html',context)


# EXAM DELETE VIEW
class AssignmentSubmissionDelete(DeleteView):
    model = AssignmentSubmission
    success_url = reverse_lazy('core:assignment-submission-list')






def FeedbackSubmission(request):
    form = FeedbackForm(request.POST)
    if request.method == 'POST':
        
        if form.is_valid():
            form.save()
            #return reverse_lazy('core/addInDiscussion.html')
            return redirect('core:assignment-submission-list')
    #success_url = reverse_lazy('core:ViewForum')   
    context ={'form':form}
    return render(request,'core/instructor/assignment_feedback.html',context)

def ViewForum(request):
    forums=forum.objects.all()
    count=forums.count()
    discussions=[]
    for i in forums:
        discussions.append(i.discussion_set.all())
 
    context={'forums':forums,
              'count':count,
              'discussions':discussions}
    return render(request,'core/ViewForum.html',context)
 
def addInForum(request):
    if request.method == 'POST':
        form = CreateInForum(request.POST)
        
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('core:ViewForum')
    #success_url = reverse_lazy('core:ViewForum')
    context ={'form':form}
    return render(request,'core/addInForum.html',context)
 
def addInDiscussion(request):
    if request.method == 'POST':
        form = CreateInDiscussion(request.POST)
        
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            #return reverse_lazy('core/addInDiscussion.html')
            return redirect('core:ViewForum')
    #success_url = reverse_lazy('core:ViewForum')   
    context ={'form':form}
    return render(request,'core/addInDiscussion.html',context)

# def CourseStats(request):
#     grades = Feedback.objects.all()#filter(AssignmentSubmission.user=request.user)
    
#     courses = Course.objects.all()

#     mar_obtained = {}
#     total = {}

#     for c in courses:

#         mar_obtained[c.course_name] = 0
#         total[c.course_name] = 0
    


#     for foo in grades:

#         mar_obtained[foo.AssignmentSubmission.Assigment.Course.course_name] += foo.AssignmentSubmission.Assignment.weight*foo.marks
#         total[foo.AssignmentSubmission.Assigment.Course.course_name] += foo.AssignmentSubmission.Assignment.weight*foo.AssignmentSubmission.Assignment.marks


#     context = {
#         'mar_obtained' : mar_obtained,
#         'total' : total
#     }

#     return render(request, 'core/student/viewstats.html' ,context)

templates/core/instructor/assignment_create.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

  <center>
  
  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
  Float - Moodle
 </font> 
  <br>
  <br>
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />  
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/accounts/login/';" value="Login" /> -->

  <br> 
  <br>
  </center>
  <font size="6"
          face="arial"
          color="black">
          Create assignment 
  </font>
  <font size="3"
          face="arial"
          color="black">
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; ">Create</button>
</form>
</font>
{% endblock %}

templates/core/instructor/assignment_submission_list.html
{% extends 'base.html' %}
<!--{% load static %}-->
{% block title %}Assignments{% endblock %}


{% block content %}
{% if request.user.is_authenticated and request.user.role == 'instructor' %}


    <div class="container">
        
        <div class="col-12 col-sm-6 col-md-10">
            <br>
            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
            <br>
                    <strong><h3>Assignments</h3></strong>
        <hr/>


           {% for foo in assignment_submission %}

            
                <p> <h4>Course Name</h4> {{ foo.Assignment.Course.course_name }} </p>


                <p> <h4>Assignment Name</h4> {{ foo.Assignment.title }} </p>

                <p> <h4>Name</h4> {{ foo.user.first_name }} {{ foo.user.last_name }}</p>

                <p> <h4>Email</h4> {{ foo.user.email }}</p>


                <!--<p> <h4>Id</h4> {{ foo.university_id }} </p>-->
                
                <p> <h4>Answer</h4> {{ foo.content }}  </p>

                {%for fee in feedbacks%}
                
                {%for objs in fee%} 
                
                {% if objs.AssignmentSubmission == foo %}
                
                <p> <h4>Feedback</h4> {{objs.feedback}} </p> 
                
                <p> <h4>Marks</h4> {{objs.marks}} </p> 

                {% endif %}
                {%endfor%} 
                {%endfor%}

                <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-feedback' %}"; value="Give Feedback" />
               
                <p> <a href="{{ foo.file.url }}"> View Submission File</a></p>
                <br/>
                <!--<a href="{% url 'core:assignment-submission-delete' foo.id %}">Delete Assignment</a>-->
                  <hr/>
            {% endfor %}




            <br/>


            <br/>


        </div>

    </div>
    {% elif request.user.is_authenticated and request.user.role == 'student' %}
    <div class="container">
        
        <div class="col-12 col-sm-6 col-md-10">
            <br>
            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
            <br>
                    <strong><h3>Assignments</h3></strong>
        <hr/>


           {% for foo in assignment_submission %}

                {% if foo.user == request.user %}
                <p> <h4>Course Name</h4> {{ foo.Assignment.Course.course_name }} </p>

                <p> <h4>Assignment Name</h4> {{ foo.Assignment.title }} </p>

                <p> <h4>Name</h4> {{ foo.user.first_name }} {{ foo.user.last_name }}</p>

                <p> <h4>Email</h4> {{ foo.user.email }}</p>


                <!--<p> <h4>Id</h4> {{ foo.university_id }} </p>-->
                
                <p> <h4>Answer</h4> {{ foo.content }}  </p>

                <!--<p> <h4>Feedback</h4> {{ foo.feedback }}  </p>-->
                {%for fee in feedbacks%}
                
                {%for objs in fee%} 
                
                {% if objs.AssignmentSubmission == foo %}
                
                <p> <h4>Feedback</h4> {{objs.feedback}} </p> 
                
                <p> <h4>Marks</h4> {{objs.marks}} </p> 

                {% endif %}
                {%endfor%} 
                {%endfor%}

                <p> <a href="{{ foo.file.url }}">View Submission File</a></p>
                <br/>
                <!--<a href="{% url 'core:assignment-submission-delete' foo.id %}">Delete Assignment</a>-->
                  <hr/>

                {% endif %}
            {% endfor %}




            <br/>


            <br/>


        </div>

    </div>
    

    {% else %}

    404 Not Found

    {% endif %}


   
{% endblock %}

templates/core/instructor/assignments.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Assignments{% endblock %}


{% block content %}

    <div class="container">

        <div class="col-12 col-sm-6 col-md-10">
            {% if request.user.is_authenticated and request.user.role == 'instructor' %}
            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
                {% for foo in assignment %}
                    <h3><strong> Course Name: {{ foo.Course.course_name }}  </strong></h3>

                    <h3><strong> Assignment Name: {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Created at</h4> {{ foo.created_at }}  </p>

                    <p> <h4>End at</h4> {{ foo.end_at }}  </p>

                    <!--<a href="{% url 'core:delete-assignment' foo.id %}">Delete Assignment</a>-->
                    <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:delete-assignment' foo.id %}"; value="Delete Assignment" />

                {% endfor %}
                <hr/>


                <!--<h4><a href="{% url 'core:assignment-create' %}">Create a Assignment</a></h4>-->
                <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-create' %}"; value="Create Assignment" />
                <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-submission-list' %}"; value="View Submissions" />

            {% else %}

            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
            <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
                {% for foo in assignment %}
                    <h3><strong> Course Name: {{ foo.Course.course_name }}  </strong></h3>

                    <h3><strong> {{ foo.title }}  </strong></h3>
                    <hr/>
                    <p> <h4>Content</h4> {{ foo.content }} </p>
                    <br/>
                    <p> <h4>Marks</h4> {{ foo.marks }} </p>

                    <p> <h4>Created at</h4> {{ foo.created_at }}  </p>

                    <p> <h4>End at</h4> {{ foo.end_at }}  </p>
                          <br/>
                      <!--<h4><a href="{% url 'core:assignment-submission' %}">Submit Assignment</a></h4>-->
                      
                  <hr/>
                {% endfor %}
                <hr/>

                <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-submission-list' %}"; value="View Submissions" />

                <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-submission' %}"; value="Solve Assignment" />
            {% endif %}
            <br/>
        </div>

    </div>

{% endblock %}

templates/core/instructor/courses.html
{% extends 'base.html' %}
<!--{% load static %}-->
{% block title %}Courses{% endblock %}


{% block content %}
{% if request.user.is_authenticated and request.user.role == 'instructor' %}


    <div class="container">
        
        <div class="col-12 col-sm-6 col-md-10">
            <br>
            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
            <br>
                    <strong><h3>Courses</h3></strong>
        <hr/>


           {% for foo in course %}
                {% if foo.user == request.user %}

                <p> <h4>Course Name</h4> {{ foo.course_name }} </p>

                <p> <h4>Name</h4>  {{ foo.user.first_name }} {{ foo.user.last_name }} </p>

                <p> <h4>Details</h4> {{ foo.course_description }} </p>

                <br/>
                <!--<a href="{% url 'core:assignment-submission-delete' foo.id %}">Delete Assignment</a>-->
                  <hr/>

                  <br>
                  <br> 
              
                  <br>
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-create' %}"; value="Create Assignment" /> 
        <br>
        <br>
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-list' %}"; value="View Assignments" /> 
            {% endif %}
            {% endfor %}

            <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:250px; height:40px; color:white; " onclick=location.href="{% url 'core:invite' %}"; value="Invite to floatmoodle" />


            <br/>


            <br/>


        </div>

    </div>
    {% elif request.user.is_authenticated and request.user.role == 'student' %}
    <div class="container">
        
        <div class="col-12 col-sm-6 col-md-10">
            <br>
            <br>
            <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/';" value="Home" />-->
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />
            <br>
            <br>
                    <strong><h3>Courses</h3></strong>
        <hr/>


           
            {% for foo in course %}

                <p> <h4>Course Name</h4> {{ foo.course_name }} </p>

                <p> <h4>Name</h4> {{ foo.user.first_name }} {{ foo.user.last_name }} </p>

                <p> <h4>Details</h4> {{ foo.course_description }} </p>

                <br/>
                <!--<a href="{% url 'core:assignment-submission-delete' foo.id %}">Delete Assignment</a>-->
                <hr/>

                 

            {% endfor %}

            <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-list' %}"; value="View Assignments" />


            <br/>


            <br/>


        </div>

    </div>
    

    {% else %}

    404 Not Found

    {% endif %}


   
{% endblock %}