authentication/urls.py
from django.urls import path
from .views import *


app_name = "authentication"

urlpatterns = [
    path('student/register/', RegisterStudentView.as_view(), name='student-register'),
    path('student/profile/update/', EditStudentProfileView.as_view(), name='student-profile-update'),
    #path('student/profile/update/', EditStudentProfileView.change_password, name='student-profile-update1'),
    path('student/password/update/', student_change_password, name='student-change-password'),
    path('instructor/register/', RegisterInstructorView.as_view(), name='instructor-register'),
    path('instructor/profile/update/', EditInstructorProfileView.as_view(), name='instructor-profile-update'),
     path('instructor/password/update/', instructor_change_password, name='instructor-change-password'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

core/urls.py
from django.urls import path

from .views import *

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

app_name = "core"

urlpatterns = [
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
                  path('invite/', InvitationView.as_view(), name = 'invite'),
                  path('course/', CourseView.as_view(), name='course'),
                  path('course-create/', CourseCreateView.as_view(), name='course-create'),                  
                  path('assignment-create/', AssignmentCreateView.as_view(), name='assignment-create'),
                  path('assignment/', AssignmentView.as_view(), name='assignment-list'),
                  path('<pk>/delete/', AssignmentDeleteView.as_view(), name='delete-assignment'),
                  path('assignment-submission/', AssignmentSubmissionView.as_view(), name='assignment-submission'),
                  path('assignment-submission-list/', AssignmentSubmissionListView, name='assignment-submission-list'),
                  path('<pk>/delete/', AssignmentSubmissionDelete.as_view(), name='assignment-submission-delete'),
                  path('assignment/feedback/',FeedbackSubmission,name='assignment-feedback'),
                  path('addInForum/',addInForum,name='addInForum'),
                  path('addInDiscussion/',addInDiscussion,name='addInDiscussion'),
                  path('ViewForum/',ViewForum,name='ViewForum'),
                 # path('ViewStats/',CourseStats,name='ViewStats'),
                  
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

floatmoodle2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('core.urls', namespace='core')),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), 
        name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% if request.user.is_authenticated and request.user.role == 'instructor' %}
    <font size="6"
            face="arial"
            color="black">
    Float - Moodle
    </font>  
    <center>
    <br>
    <h1> Welcome {{ request.user.first_name }} </h1>
    <br>
    <ul >
        <!--<li><a href="{% url 'authentication:instructor-profile-update' %}"> Edit Profile</a></li>-->
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:instructor-profile-update' %}"; value="Edit Profile" /> 
        <!--<li><a href="{% url 'authentication:logout' %}"> Logout</a></li>-->
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log Out" /> 

    </ul>

    <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:course-create' %}"; value="Create Course" /> 
    <br>
    <br>
    <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:course' %}"; value="View Courses" /> 

    <br>
    <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-create' %}"; value="Create Assignment" /> 
    <br>
    <br>
    <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-list' %}"; value="View Assignments" /> -->
    <br>
    <br>
    <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:ViewForum' %}"; value="View Forum" />

{% elif request.user.is_authenticated and request.user.role == 'student' %}
<font size="6"
face="arial"
color="black">
Float - Moodle
</font>  
<center>

    
        <h1>
            Welcome {{ request.user.first_name }}
        </h1>
    

    <ul>

        <!--<li><a href="{% url 'authentication:student-profile-update' %}"> Edit Profile</a></li>
        <li><a href="{% url 'authentication:logout' %}"> Logout</a></li>-->
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:student-profile-update' %}"; value="Edit Profile" />
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log Out" /> 
        <br>
        <br>

        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:course' %}"; value="View Courses" /> 
        <br>
        <br>
        <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:assignment-list' %}"; value="View Assignments" /> -->
        <br>
        <br>
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:ViewForum' %}"; value="View Forum" />
        
        <br>
        <br>
        <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:ViewStats' %}"; value="View Statistics" />-->

    </ul>

{% else %}
  <body>

  <center>

  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
   Float - Moodle
  </font>
  <br>
  <br>
  <h1>Register as</h1>
    <ul>
        <!--<li><a href='{% url "authentication:instructor-register" %}'> INSTRUCTOR</a></li>-->
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:instructor-register' %}"; value="INSTRUCTOR" /> 
        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:student-register' %}"; value="STUDENT" />
        <!--<li><a href="{% url 'authentication:student-register' %}"> STUDENT</a></li>-->
    </ul>
  

  
    <!--<a href="{% url 'authentication:login' %}">
        <p> Login</p>
    </a> -->

        <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:120px; height:40px; color:white; " onclick=location.href="{% url 'authentication:login' %}"; value="LOGIN" />
    


  <br>
  <br>
  
  </body> 
{% endif %}
{% endblock %}

templates/password_reset.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}


  <center>
  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
  Float - Moodle
  <br>
  <br>
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />  

  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log out" /> 
    
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/accounts/logout/';" value="Logout" /> -->

  
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/password/';" value="Change Password" />-->
  <br>
  <br>
  </center>
  
  <style>
        .tab {
            display: inline-block;
            margin-left: 300px;
        }
    </style>
 <span class="tab">

    <h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Send Email</button>
  </form>

  {% endblock %}

templates/password_reset_done.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}


  <center>
  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
  Float - Moodle
  <br>
  <br>
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />  

  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log out" /> 
    
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/accounts/logout/';" value="Logout" /> -->

  
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/password/';" value="Change Password" />-->
  <br>
  <br>
  </center>
  
  <style>
        .tab {
            display: inline-block;
            margin-left: 300px;
        }
    </style>
 <span class="tab">


    <h3>Password reset complete</h3>

    <p>Your password has been set. You may go ahead to home.</p>

  {% endblock %}

templates/password_reset_form.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}


  <center>
  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
  Float - Moodle
  <br>
  <br>
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />  

  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log out" /> 
    
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/accounts/logout/';" value="Logout" /> -->

  
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/password/';" value="Change Password" />-->
  <br>
  <br>
  </center>
  
  <style>
        .tab {
            display: inline-block;
            margin-left: 300px;
        }
    </style>
 <span class="tab">
    <h3>Enter new password</h3>

    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
    
    <form method="post">
    
        {% csrf_token %}
        {{form}}
        <input type="Submit" name="Update Password">
        
    </form>

  {% endblock %}

templates/password_reset_sent.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}


  <center>
  <br>
  <br>
  <font size="6"
          face="arial"
          color="black">
  Float - Moodle
  <br>
  <br>
  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick=location.href="{% url 'core:home' %}"; value="Home" />  

  <input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick=location.href="{% url 'authentication:logout' %}"; value="Log out" /> 
    
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:80px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/accounts/logout/';" value="Logout" /> -->

  
  <!--<input type="button" style="background-color:#0066FF; border-collapse:collapse; border-radius:5px 5px; width:160px; height:40px; color:white; " onclick="location.href='http://127.0.0.1:8000/password/';" value="Change Password" />-->
  <br>
  <br>
  </center>
  
  <style>
        .tab {
            display: inline-block;
            margin-left: 300px;
        }
    </style>
 <span class="tab">

    <h3>Password reset sent</h3>


    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
    
    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

  {% endblock %}